"""car table

Revision ID: 07908617a7be
Revises: e01c8a9dad24
Create Date: 2023-01-20 11:36:09.381523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07908617a7be'
down_revision = 'e01c8a9dad24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_car_insureded_until'), ['insureded_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_leased_until'), ['leased_until'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_leased_until'))
        batch_op.drop_index(batch_op.f('ix_car_insureded_until'))

    # ### end Alembic commands ###
