"""empty message

Revision ID: 29528ca18b48
Revises: dada9bc71c33
Create Date: 2023-02-05 09:38:04.251553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29528ca18b48'
down_revision = 'dada9bc71c33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_purpose')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_google_id'), ['google_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_google_id'))
        batch_op.drop_column('google_id')

    op.create_table('route_purpose',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.INTEGER(), nullable=True),
    sa.Column('desc', sa.VARCHAR(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    # ### end Alembic commands ###
