"""empty message

Revision ID: 7b797a903bb2
Revises: 
Create Date: 2023-02-02 15:36:45.159377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b797a903bb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_purpose',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('desc', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SPZ', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('VIN', sa.String(length=50), nullable=True),
    sa.Column('leasing_company', sa.String(length=120), nullable=True),
    sa.Column('leased_until', sa.DateTime(), nullable=True),
    sa.Column('insurance_company', sa.String(length=120), nullable=True),
    sa.Column('insured_until', sa.DateTime(), nullable=True),
    sa.Column('highway', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_car_SPZ'), ['SPZ'], unique=True)
        batch_op.create_index(batch_op.f('ix_car_VIN'), ['VIN'], unique=True)
        batch_op.create_index(batch_op.f('ix_car_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_insurance_company'), ['insurance_company'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_insured_until'), ['insured_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_leased_until'), ['leased_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_leasing_company'), ['leasing_company'], unique=False)

    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver', sa.Integer(), nullable=True),
    sa.Column('car', sa.Integer(), nullable=True),
    sa.Column('route_desc', sa.String(length=120), nullable=True),
    sa.Column('route_purpose', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('own_gas', sa.Integer(), nullable=True),
    sa.Column('route_length', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car'], ['car.id'], ),
    sa.ForeignKeyConstraint(['driver'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_route_desc'), ['route_desc'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_route_desc'))
        batch_op.drop_index(batch_op.f('ix_route_date'))

    op.drop_table('route')
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_leasing_company'))
        batch_op.drop_index(batch_op.f('ix_car_leased_until'))
        batch_op.drop_index(batch_op.f('ix_car_insured_until'))
        batch_op.drop_index(batch_op.f('ix_car_insurance_company'))
        batch_op.drop_index(batch_op.f('ix_car_description'))
        batch_op.drop_index(batch_op.f('ix_car_VIN'))
        batch_op.drop_index(batch_op.f('ix_car_SPZ'))

    op.drop_table('car')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('route_purpose')
    # ### end Alembic commands ###
