"""empty message

Revision ID: dada9bc71c33
Revises: 7b797a903bb2
Create Date: 2023-02-02 15:39:08.919648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dada9bc71c33'
down_revision = '7b797a903bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_user_name'), ['user_name'], unique=False)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_user_name'))
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
