"""user table

Revision ID: e01c8a9dad24
Revises: 
Create Date: 2023-01-20 11:32:44.364189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01c8a9dad24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SPZ', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('VIN', sa.String(length=50), nullable=True),
    sa.Column('leasing_company', sa.String(length=120), nullable=True),
    sa.Column('leased_until', sa.DateTime(), nullable=True),
    sa.Column('insurence_company', sa.String(length=120), nullable=True),
    sa.Column('insureded_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_car_SPZ'), ['SPZ'], unique=True)
        batch_op.create_index(batch_op.f('ix_car_VIN'), ['VIN'], unique=True)
        batch_op.create_index(batch_op.f('ix_car_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_insurence_company'), ['insurence_company'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_leasing_company'), ['leasing_company'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_leasing_company'))
        batch_op.drop_index(batch_op.f('ix_car_insurence_company'))
        batch_op.drop_index(batch_op.f('ix_car_description'))
        batch_op.drop_index(batch_op.f('ix_car_VIN'))
        batch_op.drop_index(batch_op.f('ix_car_SPZ'))

    op.drop_table('car')
    # ### end Alembic commands ###
